version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio
    restart: always
    ports:
      - "3000:3000"
    # Uncomment and modify these for persistent storage if needed
    # volumes:
    #   - ./data:/app/data
    environment:
      - NODE_ENV=production
    networks:
      - portfolio_network
    # Add healthcheck to ensure container is running properly
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # Optional: Add Nginx as a reverse proxy
  # nginx:
  #   image: nginx:alpine
  #   container_name: portfolio_nginx
  #   restart: always
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/conf.d:/etc/nginx/conf.d
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   depends_on:
  #     - portfolio
  #   networks:
  #     - portfolio_network

networks:
  portfolio_network:
    driver: bridge 